#!/bin/bash

export ROOTDIR=$(dirname $(realpath $0))
source ${ROOTDIR}/root/etc/profile.d/getup.sh

start_container()
{
    if $run_as_root; then
        CONTAINER_USER=root
        CONTAINER_GROUP=root
        CONTAINER_USER_ID=0
        CONTAINER_GROUP_ID=0
        CONTAINER_HOME=/root
    else
        CONTAINER_USER=$(id -un)
        CONTAINER_GROUP=$(id -gn)
        CONTAINER_USER_ID=$(id -u)
        CONTAINER_GROUP_ID=$(id -g)
        CONTAINER_HOME=/home/$CONTAINER_USER
    fi

    docker_image_repo=${docker_image_repo:-getupcloud/cluster}
    docker_image_tag=${docker_image_tag:-$(cat version.txt)}
    docker_image=${docker_image_repo}:${docker_image_tag}
    docker_command=${docker_command:-/bin/bash --login}
    docker_run_options_defaults=(
        --rm
        -it
        --env-file $ROOTDIR/.dockerenv
        -v $cluster_dir:/work
        -v $ROOTDIR:/repo
        -v $HOME/.gitconfig:$CONTAINER_HOME/.gitconfig.host
        -v $HOME/.ssh:$CONTAINER_HOME/.ssh:ro
    )

    if [ "$type" == kind ]; then
        docker_run_options_defaults+=(
            --network host
            -v /var/run/docker.sock:/var/run/docker.sock
        )
    fi

    if $devel; then
        docker_run_options_defaults+=(
            -v $ROOTDIR/root/usr/local/bin:$CONTAINER_HOME/bin
            -v $ROOTDIR/root/etc/profile.d/getup.sh:/etc/profile.d/getup.sh
        )
    fi

    {
        echo CONTAINER_USER=$CONTAINER_USER
        echo CONTAINER_GROUP=$CONTAINER_GROUP
        echo CONTAINER_USER_ID=$CONTAINER_USER_ID
        echo CONTAINER_GROUP_ID=$CONTAINER_GROUP_ID
        echo CONTAINER_HOME=$CONTAINER_HOME
        echo GH_TOKEN=$GH_TOKEN
    } > .dockerenv

    info Starting cluster: $cluster_dir with docker image ${docker_image}
    docker_run="docker run ${docker_run_options_defaults[@]} ${docker_run_options} ${docker_image_repo}:${docker_image_tag} ${docker_command}"
    info \$ $docker_run
    echo
    eval $docker_run
}

devel=false
standalone=false
cluster_dir=""
run_as_root=false

while [ $# -gt 0 ]; do
    case $1 in
        --help|-h)
            echo "Usage: $p [-s|--standaalone] [-d|--devel] [--run-as-root] -- [command...] "
            exit 0
        ;;
        --standalone|-s)
            standalone=true
        ;;
        --run-as-root|-r)
            run_as_root=true
        ;;
        --devel|-d)
            devel=true
        ;;
        --) shift
            break
        ;;
        *)
            cluster_dir=$1
    esac
    shift
done

if [ $# -gt 0 ]; then
  docker_command="$*"
  shift $#
fi

if $standalone; then
    cluster_dir="$PWD/standalone"
    mkdir -p $cluster_dir
    touch $cluster_dir/cluster.conf
    touch $cluster_dir/terraform.tfvars
    #if ! [ -e $cluster_dir/cluster.conf ]; then
    #    (
    #        customer=standalone
    #        type=standalone
    #        name=standalone
    #    ) > $cluster_dir/cluster.conf
    #fi
    start_container
    exit
fi

if [ -d "$cluster_dir" ]; then
    config_file=${cluster_dir}/cluster.conf
    if ! has_valid_config $config_file; then
        exit 1
    fi
else
    clusters=( clusters/*/*/ )
    clusters=( ${clusters[*]%/} )

    if ! [ -d "${clusters[0]}" ]; then
        warn No clusters found. Please run \`./bootstrap\` to create one.
        exit 1
    fi

    if [ ${#clusters[*]} -eq 1 ]; then
        cluster_dir=${clusters[0]}
        config_file=${cluster_dir}/cluster.conf
    else
        PS3="${COLOR_GREEN}${COLOR_BOLD}Select cluster to start: ${COLOR_RESET} "
        select cluster_dir in ${clusters[*]}; do
            config_file=$cluster_dir/cluster.conf
            if has_valid_config $config_file; then
                break
            else
                warn Config not found: $config_file
            fi
        done
    fi
fi

source_env $config_file
cluster_dir=$(realpath ${cluster_dir})

start_container $cluster_dir
