apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: monitoring
  namespace: flux-system
spec:
  values:
    kube-state-metrics:
      extraArgs:
      - --metric-labels-allowlist=nodes=[eks.amazonaws.com/capacityType]
