apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base/
- helmrelease-aws-ebs-csi-driver.yaml
- helmrelease-aws-efs-csi-driver.yaml
- helmrelease-aws-load-balancer-controller.yaml
- helmrelease-metrics-server.yaml
- helmrepository.yaml
- helmrelease-ecr-credentials-sync.yaml

patches:
- path: helmrelease-cert-manager.yaml
- path: helmrelease-cluster-autoscaler.yaml
- path: helmrelease-external-dns.yaml
- path: helmrelease-ingress-nginx.yaml
- path: helmrelease-monitoring.yaml
- path: helmrelease-velero.yaml
