#!/bin/bash

kubectl()
{
    export GIT_PS1_SHOWCOLORHINTS=true
    export GIT_PS1_SHOWDIRTYSTATE=true
    export GIT_PS1_SHOWSTASHSTATE=true
    export GIT_PS1_SHOWUNTRACKEDFILES=true
    export GIT_PS1_SHOWUPSTREAM=auto
    export KUBE_PS1_SYMBOL_USE_IMG=true

    export PROMPT_COMMAND='export PS1="$COLOR_BOLD[\u@\h \w$(__git_ps1 " git(%s)") k8s$(kube_ps1)]\$${COLOR_RESET} "'

    echo "+ kubectl $@" 1>&2;
    command kubectl "$@"
}

# alias | sed -ne "s/^alias \(k[^=]\+\)='\(kubectl\)\(.*\)/alias w\1='watch -n1 \2\3/p"
alias wka='watch -n1 kubectl apply --recursive -f'
alias wkak='watch -n1 kubectl apply -k'
alias wkd='watch -n1 kubectl describe'
alias wkdall='watch -n1 kubectl describe --all-namespaces'
alias wkdcm='watch -n1 kubectl describe configmap'
alias wkdcmall='watch -n1 kubectl describe configmap --all-namespaces'
alias wkdcml='watch -n1 kubectl describe configmap -l'
alias wkdcmn='watch -n1 kubectl describe configmap --namespace'
alias wkddep='watch -n1 kubectl describe deployment'
alias wkddepall='watch -n1 kubectl describe deployment --all-namespaces'
alias wkddepl='watch -n1 kubectl describe deployment -l'
alias wkddepn='watch -n1 kubectl describe deployment --namespace'
alias wkdf='watch -n1 kubectl describe --recursive -f'
alias wkding='watch -n1 kubectl describe ingress'
alias wkdingall='watch -n1 kubectl describe ingress --all-namespaces'
alias wkdingl='watch -n1 kubectl describe ingress -l'
alias wkdingn='watch -n1 kubectl describe ingress --namespace'
alias wkdl='watch -n1 kubectl describe -l'
alias wkdn='watch -n1 kubectl describe --namespace'
alias wkdno='watch -n1 kubectl describe nodes'
alias wkdnol='watch -n1 kubectl describe nodes -l'
alias wkdns='watch -n1 kubectl describe namespaces'
alias wkdnsall='watch -n1 kubectl describe namespaces --all-namespaces'
alias wkdnsl='watch -n1 kubectl describe namespaces -l'
alias wkdpo='watch -n1 kubectl describe pods'
alias wkdpoall='watch -n1 kubectl describe pods --all-namespaces'
alias wkdpol='watch -n1 kubectl describe pods -l'
alias wkdpon='watch -n1 kubectl describe pods --namespace'
alias wkdsec='watch -n1 kubectl describe secret'
alias wkdsecall='watch -n1 kubectl describe secret --all-namespaces'
alias wkdsecl='watch -n1 kubectl describe secret -l'
alias wkdsecn='watch -n1 kubectl describe secret --namespace'
alias wkdsvc='watch -n1 kubectl describe service'
alias wkdsvcall='watch -n1 kubectl describe service --all-namespaces'
alias wkdsvcl='watch -n1 kubectl describe service -l'
alias wkdsvcn='watch -n1 kubectl describe service --namespace'
alias wkex='watch -n1 kubectl exec -i -t'
alias wkexn='watch -n1 kubectl exec -i -t --namespace'
alias wkg='watch -n1 kubectl get'
alias wkgall='watch -n1 kubectl get --all-namespaces'
alias wkgallojson='watch -n1 kubectl get --all-namespaces -o=json'
alias wkgallowide='watch -n1 kubectl get --all-namespaces -o=wide'
alias wkgallowidesl='watch -n1 kubectl get --all-namespaces -o=wide --show-labels'
alias wkgalloyaml='watch -n1 kubectl get --all-namespaces -o=yaml'
alias wkgallsl='watch -n1 kubectl get --all-namespaces --show-labels'
alias wkgallslowide='watch -n1 kubectl get --all-namespaces --show-labels -o=wide'
alias wkgallslw='watch -n1 kubectl get --all-namespaces --show-labels --watch'
alias wkgallslwowide='watch -n1 kubectl get --all-namespaces --show-labels --watch -o=wide'
alias wkgallw='watch -n1 kubectl get --all-namespaces --watch'
alias wkgallwojson='watch -n1 kubectl get --all-namespaces --watch -o=json'
alias wkgallwowide='watch -n1 kubectl get --all-namespaces --watch -o=wide'
alias wkgallwowidesl='watch -n1 kubectl get --all-namespaces --watch -o=wide --show-labels'
alias wkgallwoyaml='watch -n1 kubectl get --all-namespaces --watch -o=yaml'
alias wkgallwsl='watch -n1 kubectl get --all-namespaces --watch --show-labels'
alias wkgallwslowide='watch -n1 kubectl get --all-namespaces --watch --show-labels -o=wide'
alias wkgcm='watch -n1 kubectl get configmap'
alias wkgcmall='watch -n1 kubectl get configmap --all-namespaces'
alias wkgcmallojson='watch -n1 kubectl get configmap --all-namespaces -o=json'
alias wkgcmallowide='watch -n1 kubectl get configmap --all-namespaces -o=wide'
alias wkgcmalloyaml='watch -n1 kubectl get configmap --all-namespaces -o=yaml'
alias wkgcmallw='watch -n1 kubectl get configmap --all-namespaces --watch'
alias wkgcmallwojson='watch -n1 kubectl get configmap --all-namespaces --watch -o=json'
alias wkgcmallwowide='watch -n1 kubectl get configmap --all-namespaces --watch -o=wide'
alias wkgcmallwoyaml='watch -n1 kubectl get configmap --all-namespaces --watch -o=yaml'
alias wkgcml='watch -n1 kubectl get configmap -l'
alias wkgcmn='watch -n1 kubectl get configmap --namespace'
alias wkgcmojson='watch -n1 kubectl get configmap -o=json'
alias wkgcmojsonall='watch -n1 kubectl get configmap -o=json --all-namespaces'
alias wkgcmojsonl='watch -n1 kubectl get configmap -o=json -l'
alias wkgcmojsonn='watch -n1 kubectl get configmap -o=json --namespace'
alias wkgcmowide='watch -n1 kubectl get configmap -o=wide'
alias wkgcmowideall='watch -n1 kubectl get configmap -o=wide --all-namespaces'
alias wkgcmowidel='watch -n1 kubectl get configmap -o=wide -l'
alias wkgcmowiden='watch -n1 kubectl get configmap -o=wide --namespace'
alias wkgcmoyaml='watch -n1 kubectl get configmap -o=yaml'
alias wkgcmoyamlall='watch -n1 kubectl get configmap -o=yaml --all-namespaces'
alias wkgcmoyamll='watch -n1 kubectl get configmap -o=yaml -l'
alias wkgcmoyamln='watch -n1 kubectl get configmap -o=yaml --namespace'
alias wkgcmw='watch -n1 kubectl get configmap --watch'
alias wkgcmwall='watch -n1 kubectl get configmap --watch --all-namespaces'
alias wkgcmwallojson='watch -n1 kubectl get configmap --watch --all-namespaces -o=json'
alias wkgcmwallowide='watch -n1 kubectl get configmap --watch --all-namespaces -o=wide'
alias wkgcmwalloyaml='watch -n1 kubectl get configmap --watch --all-namespaces -o=yaml'
alias wkgcmwl='watch -n1 kubectl get configmap --watch -l'
alias wkgcmwn='watch -n1 kubectl get configmap --watch --namespace'
alias wkgcmwojson='watch -n1 kubectl get configmap --watch -o=json'
alias wkgcmwojsonall='watch -n1 kubectl get configmap --watch -o=json --all-namespaces'
alias wkgcmwojsonl='watch -n1 kubectl get configmap --watch -o=json -l'
alias wkgcmwojsonn='watch -n1 kubectl get configmap --watch -o=json --namespace'
alias wkgcmwowide='watch -n1 kubectl get configmap --watch -o=wide'
alias wkgcmwowideall='watch -n1 kubectl get configmap --watch -o=wide --all-namespaces'
alias wkgcmwowidel='watch -n1 kubectl get configmap --watch -o=wide -l'
alias wkgcmwowiden='watch -n1 kubectl get configmap --watch -o=wide --namespace'
alias wkgcmwoyaml='watch -n1 kubectl get configmap --watch -o=yaml'
alias wkgcmwoyamlall='watch -n1 kubectl get configmap --watch -o=yaml --all-namespaces'
alias wkgcmwoyamll='watch -n1 kubectl get configmap --watch -o=yaml -l'
alias wkgcmwoyamln='watch -n1 kubectl get configmap --watch -o=yaml --namespace'
alias wkgdep='watch -n1 kubectl get deployment'
alias wkgdepall='watch -n1 kubectl get deployment --all-namespaces'
alias wkgdepallojson='watch -n1 kubectl get deployment --all-namespaces -o=json'
alias wkgdepallowide='watch -n1 kubectl get deployment --all-namespaces -o=wide'
alias wkgdepallowidesl='watch -n1 kubectl get deployment --all-namespaces -o=wide --show-labels'
alias wkgdepalloyaml='watch -n1 kubectl get deployment --all-namespaces -o=yaml'
alias wkgdepallsl='watch -n1 kubectl get deployment --all-namespaces --show-labels'
alias wkgdepallslowide='watch -n1 kubectl get deployment --all-namespaces --show-labels -o=wide'
alias wkgdepallslw='watch -n1 kubectl get deployment --all-namespaces --show-labels --watch'
alias wkgdepallslwowide='watch -n1 kubectl get deployment --all-namespaces --show-labels --watch -o=wide'
alias wkgdepallw='watch -n1 kubectl get deployment --all-namespaces --watch'
alias wkgdepallwojson='watch -n1 kubectl get deployment --all-namespaces --watch -o=json'
alias wkgdepallwowide='watch -n1 kubectl get deployment --all-namespaces --watch -o=wide'
alias wkgdepallwowidesl='watch -n1 kubectl get deployment --all-namespaces --watch -o=wide --show-labels'
alias wkgdepallwoyaml='watch -n1 kubectl get deployment --all-namespaces --watch -o=yaml'
alias wkgdepallwsl='watch -n1 kubectl get deployment --all-namespaces --watch --show-labels'
alias wkgdepallwslowide='watch -n1 kubectl get deployment --all-namespaces --watch --show-labels -o=wide'
alias wkgdepl='watch -n1 kubectl get deployment -l'
alias wkgdepn='watch -n1 kubectl get deployment --namespace'
alias wkgdepojson='watch -n1 kubectl get deployment -o=json'
alias wkgdepojsonall='watch -n1 kubectl get deployment -o=json --all-namespaces'
alias wkgdepojsonl='watch -n1 kubectl get deployment -o=json -l'
alias wkgdepojsonn='watch -n1 kubectl get deployment -o=json --namespace'
alias wkgdepowide='watch -n1 kubectl get deployment -o=wide'
alias wkgdepowideall='watch -n1 kubectl get deployment -o=wide --all-namespaces'
alias wkgdepowideallsl='watch -n1 kubectl get deployment -o=wide --all-namespaces --show-labels'
alias wkgdepowidel='watch -n1 kubectl get deployment -o=wide -l'
alias wkgdepowiden='watch -n1 kubectl get deployment -o=wide --namespace'
alias wkgdepowidesl='watch -n1 kubectl get deployment -o=wide --show-labels'
alias wkgdepowideslall='watch -n1 kubectl get deployment -o=wide --show-labels --all-namespaces'
alias wkgdepowidesll='watch -n1 kubectl get deployment -o=wide --show-labels -l'
alias wkgdepowidesln='watch -n1 kubectl get deployment -o=wide --show-labels --namespace'
alias wkgdepoyaml='watch -n1 kubectl get deployment -o=yaml'
alias wkgdepoyamlall='watch -n1 kubectl get deployment -o=yaml --all-namespaces'
alias wkgdepoyamll='watch -n1 kubectl get deployment -o=yaml -l'
alias wkgdepoyamln='watch -n1 kubectl get deployment -o=yaml --namespace'
alias wkgdepsl='watch -n1 kubectl get deployment --show-labels'
alias wkgdepslall='watch -n1 kubectl get deployment --show-labels --all-namespaces'
alias wkgdepslallowide='watch -n1 kubectl get deployment --show-labels --all-namespaces -o=wide'
alias wkgdepslallw='watch -n1 kubectl get deployment --show-labels --all-namespaces --watch'
alias wkgdepslallwowide='watch -n1 kubectl get deployment --show-labels --all-namespaces --watch -o=wide'
alias wkgdepsll='watch -n1 kubectl get deployment --show-labels -l'
alias wkgdepsln='watch -n1 kubectl get deployment --show-labels --namespace'
alias wkgdepslowide='watch -n1 kubectl get deployment --show-labels -o=wide'
alias wkgdepslowideall='watch -n1 kubectl get deployment --show-labels -o=wide --all-namespaces'
alias wkgdepslowidel='watch -n1 kubectl get deployment --show-labels -o=wide -l'
alias wkgdepslowiden='watch -n1 kubectl get deployment --show-labels -o=wide --namespace'
alias wkgdepslw='watch -n1 kubectl get deployment --show-labels --watch'
alias wkgdepslwall='watch -n1 kubectl get deployment --show-labels --watch --all-namespaces'
alias wkgdepslwallowide='watch -n1 kubectl get deployment --show-labels --watch --all-namespaces -o=wide'
alias wkgdepslwl='watch -n1 kubectl get deployment --show-labels --watch -l'
alias wkgdepslwn='watch -n1 kubectl get deployment --show-labels --watch --namespace'
alias wkgdepslwowide='watch -n1 kubectl get deployment --show-labels --watch -o=wide'
alias wkgdepslwowideall='watch -n1 kubectl get deployment --show-labels --watch -o=wide --all-namespaces'
alias wkgdepslwowidel='watch -n1 kubectl get deployment --show-labels --watch -o=wide -l'
alias wkgdepslwowiden='watch -n1 kubectl get deployment --show-labels --watch -o=wide --namespace'
alias wkgdepw='watch -n1 kubectl get deployment --watch'
alias wkgdepwall='watch -n1 kubectl get deployment --watch --all-namespaces'
alias wkgdepwallojson='watch -n1 kubectl get deployment --watch --all-namespaces -o=json'
alias wkgdepwallowide='watch -n1 kubectl get deployment --watch --all-namespaces -o=wide'
alias wkgdepwallowidesl='watch -n1 kubectl get deployment --watch --all-namespaces -o=wide --show-labels'
alias wkgdepwalloyaml='watch -n1 kubectl get deployment --watch --all-namespaces -o=yaml'
alias wkgdepwallsl='watch -n1 kubectl get deployment --watch --all-namespaces --show-labels'
alias wkgdepwallslowide='watch -n1 kubectl get deployment --watch --all-namespaces --show-labels -o=wide'
alias wkgdepwl='watch -n1 kubectl get deployment --watch -l'
alias wkgdepwn='watch -n1 kubectl get deployment --watch --namespace'
alias wkgdepwojson='watch -n1 kubectl get deployment --watch -o=json'
alias wkgdepwojsonall='watch -n1 kubectl get deployment --watch -o=json --all-namespaces'
alias wkgdepwojsonl='watch -n1 kubectl get deployment --watch -o=json -l'
alias wkgdepwojsonn='watch -n1 kubectl get deployment --watch -o=json --namespace'
alias wkgdepwowide='watch -n1 kubectl get deployment --watch -o=wide'
alias wkgdepwowideall='watch -n1 kubectl get deployment --watch -o=wide --all-namespaces'
alias wkgdepwowideallsl='watch -n1 kubectl get deployment --watch -o=wide --all-namespaces --show-labels'
alias wkgdepwowidel='watch -n1 kubectl get deployment --watch -o=wide -l'
alias wkgdepwowiden='watch -n1 kubectl get deployment --watch -o=wide --namespace'
alias wkgdepwowidesl='watch -n1 kubectl get deployment --watch -o=wide --show-labels'
alias wkgdepwowideslall='watch -n1 kubectl get deployment --watch -o=wide --show-labels --all-namespaces'
alias wkgdepwowidesll='watch -n1 kubectl get deployment --watch -o=wide --show-labels -l'
alias wkgdepwowidesln='watch -n1 kubectl get deployment --watch -o=wide --show-labels --namespace'
alias wkgdepwoyaml='watch -n1 kubectl get deployment --watch -o=yaml'
alias wkgdepwoyamlall='watch -n1 kubectl get deployment --watch -o=yaml --all-namespaces'
alias wkgdepwoyamll='watch -n1 kubectl get deployment --watch -o=yaml -l'
alias wkgdepwoyamln='watch -n1 kubectl get deployment --watch -o=yaml --namespace'
alias wkgdepwsl='watch -n1 kubectl get deployment --watch --show-labels'
alias wkgdepwslall='watch -n1 kubectl get deployment --watch --show-labels --all-namespaces'
alias wkgdepwslallowide='watch -n1 kubectl get deployment --watch --show-labels --all-namespaces -o=wide'
alias wkgdepwsll='watch -n1 kubectl get deployment --watch --show-labels -l'
alias wkgdepwsln='watch -n1 kubectl get deployment --watch --show-labels --namespace'
alias wkgdepwslowide='watch -n1 kubectl get deployment --watch --show-labels -o=wide'
alias wkgdepwslowideall='watch -n1 kubectl get deployment --watch --show-labels -o=wide --all-namespaces'
alias wkgdepwslowidel='watch -n1 kubectl get deployment --watch --show-labels -o=wide -l'
alias wkgdepwslowiden='watch -n1 kubectl get deployment --watch --show-labels -o=wide --namespace'
alias wkgf='watch -n1 kubectl get --recursive -f'
alias wkging='watch -n1 kubectl get ingress'
alias wkgingall='watch -n1 kubectl get ingress --all-namespaces'
alias wkgingallojson='watch -n1 kubectl get ingress --all-namespaces -o=json'
alias wkgingallowide='watch -n1 kubectl get ingress --all-namespaces -o=wide'
alias wkgingalloyaml='watch -n1 kubectl get ingress --all-namespaces -o=yaml'
alias wkgingallw='watch -n1 kubectl get ingress --all-namespaces --watch'
alias wkgingallwojson='watch -n1 kubectl get ingress --all-namespaces --watch -o=json'
alias wkgingallwowide='watch -n1 kubectl get ingress --all-namespaces --watch -o=wide'
alias wkgingallwoyaml='watch -n1 kubectl get ingress --all-namespaces --watch -o=yaml'
alias wkgingl='watch -n1 kubectl get ingress -l'
alias wkgingn='watch -n1 kubectl get ingress --namespace'
alias wkgingojson='watch -n1 kubectl get ingress -o=json'
alias wkgingojsonall='watch -n1 kubectl get ingress -o=json --all-namespaces'
alias wkgingojsonl='watch -n1 kubectl get ingress -o=json -l'
alias wkgingojsonn='watch -n1 kubectl get ingress -o=json --namespace'
alias wkgingowide='watch -n1 kubectl get ingress -o=wide'
alias wkgingowideall='watch -n1 kubectl get ingress -o=wide --all-namespaces'
alias wkgingowidel='watch -n1 kubectl get ingress -o=wide -l'
alias wkgingowiden='watch -n1 kubectl get ingress -o=wide --namespace'
alias wkgingoyaml='watch -n1 kubectl get ingress -o=yaml'
alias wkgingoyamlall='watch -n1 kubectl get ingress -o=yaml --all-namespaces'
alias wkgingoyamll='watch -n1 kubectl get ingress -o=yaml -l'
alias wkgingoyamln='watch -n1 kubectl get ingress -o=yaml --namespace'
alias wkgingw='watch -n1 kubectl get ingress --watch'
alias wkgingwall='watch -n1 kubectl get ingress --watch --all-namespaces'
alias wkgingwallojson='watch -n1 kubectl get ingress --watch --all-namespaces -o=json'
alias wkgingwallowide='watch -n1 kubectl get ingress --watch --all-namespaces -o=wide'
alias wkgingwalloyaml='watch -n1 kubectl get ingress --watch --all-namespaces -o=yaml'
alias wkgingwl='watch -n1 kubectl get ingress --watch -l'
alias wkgingwn='watch -n1 kubectl get ingress --watch --namespace'
alias wkgingwojson='watch -n1 kubectl get ingress --watch -o=json'
alias wkgingwojsonall='watch -n1 kubectl get ingress --watch -o=json --all-namespaces'
alias wkgingwojsonl='watch -n1 kubectl get ingress --watch -o=json -l'
alias wkgingwojsonn='watch -n1 kubectl get ingress --watch -o=json --namespace'
alias wkgingwowide='watch -n1 kubectl get ingress --watch -o=wide'
alias wkgingwowideall='watch -n1 kubectl get ingress --watch -o=wide --all-namespaces'
alias wkgingwowidel='watch -n1 kubectl get ingress --watch -o=wide -l'
alias wkgingwowiden='watch -n1 kubectl get ingress --watch -o=wide --namespace'
alias wkgingwoyaml='watch -n1 kubectl get ingress --watch -o=yaml'
alias wkgingwoyamlall='watch -n1 kubectl get ingress --watch -o=yaml --all-namespaces'
alias wkgingwoyamll='watch -n1 kubectl get ingress --watch -o=yaml -l'
alias wkgingwoyamln='watch -n1 kubectl get ingress --watch -o=yaml --namespace'
alias wkgl='watch -n1 kubectl get -l'
alias wkgn='watch -n1 kubectl get --namespace'
alias wkgno='watch -n1 kubectl get nodes'
alias wkgnol='watch -n1 kubectl get nodes -l'
alias wkgnoojson='watch -n1 kubectl get nodes -o=json'
alias wkgnoojsonl='watch -n1 kubectl get nodes -o=json -l'
alias wkgnoowide='watch -n1 kubectl get nodes -o=wide'
alias wkgnoowidel='watch -n1 kubectl get nodes -o=wide -l'
alias wkgnooyaml='watch -n1 kubectl get nodes -o=yaml'
alias wkgnooyamll='watch -n1 kubectl get nodes -o=yaml -l'
alias wkgnow='watch -n1 kubectl get nodes --watch'
alias wkgnowl='watch -n1 kubectl get nodes --watch -l'
alias wkgnowojson='watch -n1 kubectl get nodes --watch -o=json'
alias wkgnowojsonl='watch -n1 kubectl get nodes --watch -o=json -l'
alias wkgnowowide='watch -n1 kubectl get nodes --watch -o=wide'
alias wkgnowowidel='watch -n1 kubectl get nodes --watch -o=wide -l'
alias wkgnowoyaml='watch -n1 kubectl get nodes --watch -o=yaml'
alias wkgnowoyamll='watch -n1 kubectl get nodes --watch -o=yaml -l'
alias wkgns='watch -n1 kubectl get namespaces'
alias wkgnsall='watch -n1 kubectl get namespaces --all-namespaces'
alias wkgnsallojson='watch -n1 kubectl get namespaces --all-namespaces -o=json'
alias wkgnsallowide='watch -n1 kubectl get namespaces --all-namespaces -o=wide'
alias wkgnsalloyaml='watch -n1 kubectl get namespaces --all-namespaces -o=yaml'
alias wkgnsallw='watch -n1 kubectl get namespaces --all-namespaces --watch'
alias wkgnsallwojson='watch -n1 kubectl get namespaces --all-namespaces --watch -o=json'
alias wkgnsallwowide='watch -n1 kubectl get namespaces --all-namespaces --watch -o=wide'
alias wkgnsallwoyaml='watch -n1 kubectl get namespaces --all-namespaces --watch -o=yaml'
alias wkgnsl='watch -n1 kubectl get namespaces -l'
alias wkgnsojson='watch -n1 kubectl get namespaces -o=json'
alias wkgnsojsonall='watch -n1 kubectl get namespaces -o=json --all-namespaces'
alias wkgnsojsonl='watch -n1 kubectl get namespaces -o=json -l'
alias wkgnsowide='watch -n1 kubectl get namespaces -o=wide'
alias wkgnsowideall='watch -n1 kubectl get namespaces -o=wide --all-namespaces'
alias wkgnsowidel='watch -n1 kubectl get namespaces -o=wide -l'
alias wkgnsoyaml='watch -n1 kubectl get namespaces -o=yaml'
alias wkgnsoyamlall='watch -n1 kubectl get namespaces -o=yaml --all-namespaces'
alias wkgnsoyamll='watch -n1 kubectl get namespaces -o=yaml -l'
alias wkgnsw='watch -n1 kubectl get namespaces --watch'
alias wkgnswall='watch -n1 kubectl get namespaces --watch --all-namespaces'
alias wkgnswallojson='watch -n1 kubectl get namespaces --watch --all-namespaces -o=json'
alias wkgnswallowide='watch -n1 kubectl get namespaces --watch --all-namespaces -o=wide'
alias wkgnswalloyaml='watch -n1 kubectl get namespaces --watch --all-namespaces -o=yaml'
alias wkgnswl='watch -n1 kubectl get namespaces --watch -l'
alias wkgnswojson='watch -n1 kubectl get namespaces --watch -o=json'
alias wkgnswojsonall='watch -n1 kubectl get namespaces --watch -o=json --all-namespaces'
alias wkgnswojsonl='watch -n1 kubectl get namespaces --watch -o=json -l'
alias wkgnswowide='watch -n1 kubectl get namespaces --watch -o=wide'
alias wkgnswowideall='watch -n1 kubectl get namespaces --watch -o=wide --all-namespaces'
alias wkgnswowidel='watch -n1 kubectl get namespaces --watch -o=wide -l'
alias wkgnswoyaml='watch -n1 kubectl get namespaces --watch -o=yaml'
alias wkgnswoyamlall='watch -n1 kubectl get namespaces --watch -o=yaml --all-namespaces'
alias wkgnswoyamll='watch -n1 kubectl get namespaces --watch -o=yaml -l'
alias wkgojson='watch -n1 kubectl get -o=json'
alias wkgojsonall='watch -n1 kubectl get -o=json --all-namespaces'
alias wkgojsonf='watch -n1 kubectl get -o=json --recursive -f'
alias wkgojsonl='watch -n1 kubectl get -o=json -l'
alias wkgojsonn='watch -n1 kubectl get -o=json --namespace'
alias wkgowide='watch -n1 kubectl get -o=wide'
alias wkgowideall='watch -n1 kubectl get -o=wide --all-namespaces'
alias wkgowideallsl='watch -n1 kubectl get -o=wide --all-namespaces --show-labels'
alias wkgowidef='watch -n1 kubectl get -o=wide --recursive -f'
alias wkgowidel='watch -n1 kubectl get -o=wide -l'
alias wkgowiden='watch -n1 kubectl get -o=wide --namespace'
alias wkgowidesl='watch -n1 kubectl get -o=wide --show-labels'
alias wkgowideslall='watch -n1 kubectl get -o=wide --show-labels --all-namespaces'
alias wkgowideslf='watch -n1 kubectl get -o=wide --show-labels --recursive -f'
alias wkgowidesll='watch -n1 kubectl get -o=wide --show-labels -l'
alias wkgowidesln='watch -n1 kubectl get -o=wide --show-labels --namespace'
alias wkgoyaml='watch -n1 kubectl get -o=yaml'
alias wkgoyamlall='watch -n1 kubectl get -o=yaml --all-namespaces'
alias wkgoyamlf='watch -n1 kubectl get -o=yaml --recursive -f'
alias wkgoyamll='watch -n1 kubectl get -o=yaml -l'
alias wkgoyamln='watch -n1 kubectl get -o=yaml --namespace'
alias wkgpo='watch -n1 kubectl get pods'
alias wkgpoall='watch -n1 kubectl get pods --all-namespaces'
alias wkgpoallojson='watch -n1 kubectl get pods --all-namespaces -o=json'
alias wkgpoallowide='watch -n1 kubectl get pods --all-namespaces -o=wide'
alias wkgpoallowidesl='watch -n1 kubectl get pods --all-namespaces -o=wide --show-labels'
alias wkgpoalloyaml='watch -n1 kubectl get pods --all-namespaces -o=yaml'
alias wkgpoallsl='watch -n1 kubectl get pods --all-namespaces --show-labels'
alias wkgpoallslowide='watch -n1 kubectl get pods --all-namespaces --show-labels -o=wide'
alias wkgpoallslw='watch -n1 kubectl get pods --all-namespaces --show-labels --watch'
alias wkgpoallslwowide='watch -n1 kubectl get pods --all-namespaces --show-labels --watch -o=wide'
alias wkgpoallw='watch -n1 kubectl get pods --all-namespaces --watch'
alias wkgpoallwojson='watch -n1 kubectl get pods --all-namespaces --watch -o=json'
alias wkgpoallwowide='watch -n1 kubectl get pods --all-namespaces --watch -o=wide'
alias wkgpoallwowidesl='watch -n1 kubectl get pods --all-namespaces --watch -o=wide --show-labels'
alias wkgpoallwoyaml='watch -n1 kubectl get pods --all-namespaces --watch -o=yaml'
alias wkgpoallwsl='watch -n1 kubectl get pods --all-namespaces --watch --show-labels'
alias wkgpoallwslowide='watch -n1 kubectl get pods --all-namespaces --watch --show-labels -o=wide'
alias wkgpol='watch -n1 kubectl get pods -l'
alias wkgpon='watch -n1 kubectl get pods --namespace'
alias wkgpoojson='watch -n1 kubectl get pods -o=json'
alias wkgpoojsonall='watch -n1 kubectl get pods -o=json --all-namespaces'
alias wkgpoojsonl='watch -n1 kubectl get pods -o=json -l'
alias wkgpoojsonn='watch -n1 kubectl get pods -o=json --namespace'
alias wkgpoowide='watch -n1 kubectl get pods -o=wide'
alias wkgpoowideall='watch -n1 kubectl get pods -o=wide --all-namespaces'
alias wkgpoowideallsl='watch -n1 kubectl get pods -o=wide --all-namespaces --show-labels'
alias wkgpoowidel='watch -n1 kubectl get pods -o=wide -l'
alias wkgpoowiden='watch -n1 kubectl get pods -o=wide --namespace'
alias wkgpoowidesl='watch -n1 kubectl get pods -o=wide --show-labels'
alias wkgpoowideslall='watch -n1 kubectl get pods -o=wide --show-labels --all-namespaces'
alias wkgpoowidesll='watch -n1 kubectl get pods -o=wide --show-labels -l'
alias wkgpoowidesln='watch -n1 kubectl get pods -o=wide --show-labels --namespace'
alias wkgpooyaml='watch -n1 kubectl get pods -o=yaml'
alias wkgpooyamlall='watch -n1 kubectl get pods -o=yaml --all-namespaces'
alias wkgpooyamll='watch -n1 kubectl get pods -o=yaml -l'
alias wkgpooyamln='watch -n1 kubectl get pods -o=yaml --namespace'
alias wkgposl='watch -n1 kubectl get pods --show-labels'
alias wkgposlall='watch -n1 kubectl get pods --show-labels --all-namespaces'
alias wkgposlallowide='watch -n1 kubectl get pods --show-labels --all-namespaces -o=wide'
alias wkgposlallw='watch -n1 kubectl get pods --show-labels --all-namespaces --watch'
alias wkgposlallwowide='watch -n1 kubectl get pods --show-labels --all-namespaces --watch -o=wide'
alias wkgposll='watch -n1 kubectl get pods --show-labels -l'
alias wkgposln='watch -n1 kubectl get pods --show-labels --namespace'
alias wkgposlowide='watch -n1 kubectl get pods --show-labels -o=wide'
alias wkgposlowideall='watch -n1 kubectl get pods --show-labels -o=wide --all-namespaces'
alias wkgposlowidel='watch -n1 kubectl get pods --show-labels -o=wide -l'
alias wkgposlowiden='watch -n1 kubectl get pods --show-labels -o=wide --namespace'
alias wkgposlw='watch -n1 kubectl get pods --show-labels --watch'
alias wkgposlwall='watch -n1 kubectl get pods --show-labels --watch --all-namespaces'
alias wkgposlwallowide='watch -n1 kubectl get pods --show-labels --watch --all-namespaces -o=wide'
alias wkgposlwl='watch -n1 kubectl get pods --show-labels --watch -l'
alias wkgposlwn='watch -n1 kubectl get pods --show-labels --watch --namespace'
alias wkgposlwowide='watch -n1 kubectl get pods --show-labels --watch -o=wide'
alias wkgposlwowideall='watch -n1 kubectl get pods --show-labels --watch -o=wide --all-namespaces'
alias wkgposlwowidel='watch -n1 kubectl get pods --show-labels --watch -o=wide -l'
alias wkgposlwowiden='watch -n1 kubectl get pods --show-labels --watch -o=wide --namespace'
alias wkgpow='watch -n1 kubectl get pods --watch'
alias wkgpowall='watch -n1 kubectl get pods --watch --all-namespaces'
alias wkgpowallojson='watch -n1 kubectl get pods --watch --all-namespaces -o=json'
alias wkgpowallowide='watch -n1 kubectl get pods --watch --all-namespaces -o=wide'
alias wkgpowallowidesl='watch -n1 kubectl get pods --watch --all-namespaces -o=wide --show-labels'
alias wkgpowalloyaml='watch -n1 kubectl get pods --watch --all-namespaces -o=yaml'
alias wkgpowallsl='watch -n1 kubectl get pods --watch --all-namespaces --show-labels'
alias wkgpowallslowide='watch -n1 kubectl get pods --watch --all-namespaces --show-labels -o=wide'
alias wkgpowl='watch -n1 kubectl get pods --watch -l'
alias wkgpown='watch -n1 kubectl get pods --watch --namespace'
alias wkgpowojson='watch -n1 kubectl get pods --watch -o=json'
alias wkgpowojsonall='watch -n1 kubectl get pods --watch -o=json --all-namespaces'
alias wkgpowojsonl='watch -n1 kubectl get pods --watch -o=json -l'
alias wkgpowojsonn='watch -n1 kubectl get pods --watch -o=json --namespace'
alias wkgpowowide='watch -n1 kubectl get pods --watch -o=wide'
alias wkgpowowideall='watch -n1 kubectl get pods --watch -o=wide --all-namespaces'
alias wkgpowowideallsl='watch -n1 kubectl get pods --watch -o=wide --all-namespaces --show-labels'
alias wkgpowowidel='watch -n1 kubectl get pods --watch -o=wide -l'
alias wkgpowowiden='watch -n1 kubectl get pods --watch -o=wide --namespace'
alias wkgpowowidesl='watch -n1 kubectl get pods --watch -o=wide --show-labels'
alias wkgpowowideslall='watch -n1 kubectl get pods --watch -o=wide --show-labels --all-namespaces'
alias wkgpowowidesll='watch -n1 kubectl get pods --watch -o=wide --show-labels -l'
alias wkgpowowidesln='watch -n1 kubectl get pods --watch -o=wide --show-labels --namespace'
alias wkgpowoyaml='watch -n1 kubectl get pods --watch -o=yaml'
alias wkgpowoyamlall='watch -n1 kubectl get pods --watch -o=yaml --all-namespaces'
alias wkgpowoyamll='watch -n1 kubectl get pods --watch -o=yaml -l'
alias wkgpowoyamln='watch -n1 kubectl get pods --watch -o=yaml --namespace'
alias wkgpowsl='watch -n1 kubectl get pods --watch --show-labels'
alias wkgpowslall='watch -n1 kubectl get pods --watch --show-labels --all-namespaces'
alias wkgpowslallowide='watch -n1 kubectl get pods --watch --show-labels --all-namespaces -o=wide'
alias wkgpowsll='watch -n1 kubectl get pods --watch --show-labels -l'
alias wkgpowsln='watch -n1 kubectl get pods --watch --show-labels --namespace'
alias wkgpowslowide='watch -n1 kubectl get pods --watch --show-labels -o=wide'
alias wkgpowslowideall='watch -n1 kubectl get pods --watch --show-labels -o=wide --all-namespaces'
alias wkgpowslowidel='watch -n1 kubectl get pods --watch --show-labels -o=wide -l'
alias wkgpowslowiden='watch -n1 kubectl get pods --watch --show-labels -o=wide --namespace'
alias wkgsec='watch -n1 kubectl get secret'
alias wkgsecall='watch -n1 kubectl get secret --all-namespaces'
alias wkgsecallojson='watch -n1 kubectl get secret --all-namespaces -o=json'
alias wkgsecallowide='watch -n1 kubectl get secret --all-namespaces -o=wide'
alias wkgsecalloyaml='watch -n1 kubectl get secret --all-namespaces -o=yaml'
alias wkgsecallw='watch -n1 kubectl get secret --all-namespaces --watch'
alias wkgsecallwojson='watch -n1 kubectl get secret --all-namespaces --watch -o=json'
alias wkgsecallwowide='watch -n1 kubectl get secret --all-namespaces --watch -o=wide'
alias wkgsecallwoyaml='watch -n1 kubectl get secret --all-namespaces --watch -o=yaml'
alias wkgsecl='watch -n1 kubectl get secret -l'
alias wkgsecn='watch -n1 kubectl get secret --namespace'
alias wkgsecojson='watch -n1 kubectl get secret -o=json'
alias wkgsecojsonall='watch -n1 kubectl get secret -o=json --all-namespaces'
alias wkgsecojsonl='watch -n1 kubectl get secret -o=json -l'
alias wkgsecojsonn='watch -n1 kubectl get secret -o=json --namespace'
alias wkgsecowide='watch -n1 kubectl get secret -o=wide'
alias wkgsecowideall='watch -n1 kubectl get secret -o=wide --all-namespaces'
alias wkgsecowidel='watch -n1 kubectl get secret -o=wide -l'
alias wkgsecowiden='watch -n1 kubectl get secret -o=wide --namespace'
alias wkgsecoyaml='watch -n1 kubectl get secret -o=yaml'
alias wkgsecoyamlall='watch -n1 kubectl get secret -o=yaml --all-namespaces'
alias wkgsecoyamll='watch -n1 kubectl get secret -o=yaml -l'
alias wkgsecoyamln='watch -n1 kubectl get secret -o=yaml --namespace'
alias wkgsecw='watch -n1 kubectl get secret --watch'
alias wkgsecwall='watch -n1 kubectl get secret --watch --all-namespaces'
alias wkgsecwallojson='watch -n1 kubectl get secret --watch --all-namespaces -o=json'
alias wkgsecwallowide='watch -n1 kubectl get secret --watch --all-namespaces -o=wide'
alias wkgsecwalloyaml='watch -n1 kubectl get secret --watch --all-namespaces -o=yaml'
alias wkgsecwl='watch -n1 kubectl get secret --watch -l'
alias wkgsecwn='watch -n1 kubectl get secret --watch --namespace'
alias wkgsecwojson='watch -n1 kubectl get secret --watch -o=json'
alias wkgsecwojsonall='watch -n1 kubectl get secret --watch -o=json --all-namespaces'
alias wkgsecwojsonl='watch -n1 kubectl get secret --watch -o=json -l'
alias wkgsecwojsonn='watch -n1 kubectl get secret --watch -o=json --namespace'
alias wkgsecwowide='watch -n1 kubectl get secret --watch -o=wide'
alias wkgsecwowideall='watch -n1 kubectl get secret --watch -o=wide --all-namespaces'
alias wkgsecwowidel='watch -n1 kubectl get secret --watch -o=wide -l'
alias wkgsecwowiden='watch -n1 kubectl get secret --watch -o=wide --namespace'
alias wkgsecwoyaml='watch -n1 kubectl get secret --watch -o=yaml'
alias wkgsecwoyamlall='watch -n1 kubectl get secret --watch -o=yaml --all-namespaces'
alias wkgsecwoyamll='watch -n1 kubectl get secret --watch -o=yaml -l'
alias wkgsecwoyamln='watch -n1 kubectl get secret --watch -o=yaml --namespace'
alias wkgsl='watch -n1 kubectl get --show-labels'
alias wkgslall='watch -n1 kubectl get --show-labels --all-namespaces'
alias wkgslallowide='watch -n1 kubectl get --show-labels --all-namespaces -o=wide'
alias wkgslallw='watch -n1 kubectl get --show-labels --all-namespaces --watch'
alias wkgslallwowide='watch -n1 kubectl get --show-labels --all-namespaces --watch -o=wide'
alias wkgslf='watch -n1 kubectl get --show-labels --recursive -f'
alias wkgsll='watch -n1 kubectl get --show-labels -l'
alias wkgsln='watch -n1 kubectl get --show-labels --namespace'
alias wkgslowide='watch -n1 kubectl get --show-labels -o=wide'
alias wkgslowideall='watch -n1 kubectl get --show-labels -o=wide --all-namespaces'
alias wkgslowidef='watch -n1 kubectl get --show-labels -o=wide --recursive -f'
alias wkgslowidel='watch -n1 kubectl get --show-labels -o=wide -l'
alias wkgslowiden='watch -n1 kubectl get --show-labels -o=wide --namespace'
alias wkgslw='watch -n1 kubectl get --show-labels --watch'
alias wkgslwall='watch -n1 kubectl get --show-labels --watch --all-namespaces'
alias wkgslwallowide='watch -n1 kubectl get --show-labels --watch --all-namespaces -o=wide'
alias wkgslwf='watch -n1 kubectl get --show-labels --watch --recursive -f'
alias wkgslwl='watch -n1 kubectl get --show-labels --watch -l'
alias wkgslwn='watch -n1 kubectl get --show-labels --watch --namespace'
alias wkgslwowide='watch -n1 kubectl get --show-labels --watch -o=wide'
alias wkgslwowideall='watch -n1 kubectl get --show-labels --watch -o=wide --all-namespaces'
alias wkgslwowidef='watch -n1 kubectl get --show-labels --watch -o=wide --recursive -f'
alias wkgslwowidel='watch -n1 kubectl get --show-labels --watch -o=wide -l'
alias wkgslwowiden='watch -n1 kubectl get --show-labels --watch -o=wide --namespace'
alias wkgsvc='watch -n1 kubectl get service'
alias wkgsvcall='watch -n1 kubectl get service --all-namespaces'
alias wkgsvcallojson='watch -n1 kubectl get service --all-namespaces -o=json'
alias wkgsvcallowide='watch -n1 kubectl get service --all-namespaces -o=wide'
alias wkgsvcalloyaml='watch -n1 kubectl get service --all-namespaces -o=yaml'
alias wkgsvcallw='watch -n1 kubectl get service --all-namespaces --watch'
alias wkgsvcallwojson='watch -n1 kubectl get service --all-namespaces --watch -o=json'
alias wkgsvcallwowide='watch -n1 kubectl get service --all-namespaces --watch -o=wide'
alias wkgsvcallwoyaml='watch -n1 kubectl get service --all-namespaces --watch -o=yaml'
alias wkgsvcl='watch -n1 kubectl get service -l'
alias wkgsvcn='watch -n1 kubectl get service --namespace'
alias wkgsvcojson='watch -n1 kubectl get service -o=json'
alias wkgsvcojsonall='watch -n1 kubectl get service -o=json --all-namespaces'
alias wkgsvcojsonl='watch -n1 kubectl get service -o=json -l'
alias wkgsvcojsonn='watch -n1 kubectl get service -o=json --namespace'
alias wkgsvcowide='watch -n1 kubectl get service -o=wide'
alias wkgsvcowideall='watch -n1 kubectl get service -o=wide --all-namespaces'
alias wkgsvcowidel='watch -n1 kubectl get service -o=wide -l'
alias wkgsvcowiden='watch -n1 kubectl get service -o=wide --namespace'
alias wkgsvcoyaml='watch -n1 kubectl get service -o=yaml'
alias wkgsvcoyamlall='watch -n1 kubectl get service -o=yaml --all-namespaces'
alias wkgsvcoyamll='watch -n1 kubectl get service -o=yaml -l'
alias wkgsvcoyamln='watch -n1 kubectl get service -o=yaml --namespace'
alias wkgsvcw='watch -n1 kubectl get service --watch'
alias wkgsvcwall='watch -n1 kubectl get service --watch --all-namespaces'
alias wkgsvcwallojson='watch -n1 kubectl get service --watch --all-namespaces -o=json'
alias wkgsvcwallowide='watch -n1 kubectl get service --watch --all-namespaces -o=wide'
alias wkgsvcwalloyaml='watch -n1 kubectl get service --watch --all-namespaces -o=yaml'
alias wkgsvcwl='watch -n1 kubectl get service --watch -l'
alias wkgsvcwn='watch -n1 kubectl get service --watch --namespace'
alias wkgsvcwojson='watch -n1 kubectl get service --watch -o=json'
alias wkgsvcwojsonall='watch -n1 kubectl get service --watch -o=json --all-namespaces'
alias wkgsvcwojsonl='watch -n1 kubectl get service --watch -o=json -l'
alias wkgsvcwojsonn='watch -n1 kubectl get service --watch -o=json --namespace'
alias wkgsvcwowide='watch -n1 kubectl get service --watch -o=wide'
alias wkgsvcwowideall='watch -n1 kubectl get service --watch -o=wide --all-namespaces'
alias wkgsvcwowidel='watch -n1 kubectl get service --watch -o=wide -l'
alias wkgsvcwowiden='watch -n1 kubectl get service --watch -o=wide --namespace'
alias wkgsvcwoyaml='watch -n1 kubectl get service --watch -o=yaml'
alias wkgsvcwoyamlall='watch -n1 kubectl get service --watch -o=yaml --all-namespaces'
alias wkgsvcwoyamll='watch -n1 kubectl get service --watch -o=yaml -l'
alias wkgsvcwoyamln='watch -n1 kubectl get service --watch -o=yaml --namespace'
alias wkgw='watch -n1 kubectl get --watch'
alias wkgwall='watch -n1 kubectl get --watch --all-namespaces'
alias wkgwallojson='watch -n1 kubectl get --watch --all-namespaces -o=json'
alias wkgwallowide='watch -n1 kubectl get --watch --all-namespaces -o=wide'
alias wkgwallowidesl='watch -n1 kubectl get --watch --all-namespaces -o=wide --show-labels'
alias wkgwalloyaml='watch -n1 kubectl get --watch --all-namespaces -o=yaml'
alias wkgwallsl='watch -n1 kubectl get --watch --all-namespaces --show-labels'
alias wkgwallslowide='watch -n1 kubectl get --watch --all-namespaces --show-labels -o=wide'
alias wkgwf='watch -n1 kubectl get --watch --recursive -f'
alias wkgwl='watch -n1 kubectl get --watch -l'
alias wkgwn='watch -n1 kubectl get --watch --namespace'
alias wkgwojson='watch -n1 kubectl get --watch -o=json'
alias wkgwojsonall='watch -n1 kubectl get --watch -o=json --all-namespaces'
alias wkgwojsonf='watch -n1 kubectl get --watch -o=json --recursive -f'
alias wkgwojsonl='watch -n1 kubectl get --watch -o=json -l'
alias wkgwojsonn='watch -n1 kubectl get --watch -o=json --namespace'
alias wkgwowide='watch -n1 kubectl get --watch -o=wide'
alias wkgwowideall='watch -n1 kubectl get --watch -o=wide --all-namespaces'
alias wkgwowideallsl='watch -n1 kubectl get --watch -o=wide --all-namespaces --show-labels'
alias wkgwowidef='watch -n1 kubectl get --watch -o=wide --recursive -f'
alias wkgwowidel='watch -n1 kubectl get --watch -o=wide -l'
alias wkgwowiden='watch -n1 kubectl get --watch -o=wide --namespace'
alias wkgwowidesl='watch -n1 kubectl get --watch -o=wide --show-labels'
alias wkgwowideslall='watch -n1 kubectl get --watch -o=wide --show-labels --all-namespaces'
alias wkgwowideslf='watch -n1 kubectl get --watch -o=wide --show-labels --recursive -f'
alias wkgwowidesll='watch -n1 kubectl get --watch -o=wide --show-labels -l'
alias wkgwowidesln='watch -n1 kubectl get --watch -o=wide --show-labels --namespace'
alias wkgwoyaml='watch -n1 kubectl get --watch -o=yaml'
alias wkgwoyamlall='watch -n1 kubectl get --watch -o=yaml --all-namespaces'
alias wkgwoyamlf='watch -n1 kubectl get --watch -o=yaml --recursive -f'
alias wkgwoyamll='watch -n1 kubectl get --watch -o=yaml -l'
alias wkgwoyamln='watch -n1 kubectl get --watch -o=yaml --namespace'
alias wkgwsl='watch -n1 kubectl get --watch --show-labels'
alias wkgwslall='watch -n1 kubectl get --watch --show-labels --all-namespaces'
alias wkgwslallowide='watch -n1 kubectl get --watch --show-labels --all-namespaces -o=wide'
alias wkgwslf='watch -n1 kubectl get --watch --show-labels --recursive -f'
alias wkgwsll='watch -n1 kubectl get --watch --show-labels -l'
alias wkgwsln='watch -n1 kubectl get --watch --show-labels --namespace'
alias wkgwslowide='watch -n1 kubectl get --watch --show-labels -o=wide'
alias wkgwslowideall='watch -n1 kubectl get --watch --show-labels -o=wide --all-namespaces'
alias wkgwslowidef='watch -n1 kubectl get --watch --show-labels -o=wide --recursive -f'
alias wkgwslowidel='watch -n1 kubectl get --watch --show-labels -o=wide -l'
alias wkgwslowiden='watch -n1 kubectl get --watch --show-labels -o=wide --namespace'
alias wkk='watch -n1 kubectl kustomize'
alias wklo='watch -n1 kubectl logs -f'
alias wklon='watch -n1 kubectl logs -f --namespace'
alias wklop='watch -n1 kubectl logs -f -p'
alias wkp='watch -n1 kubectl proxy'
alias wkpf='watch -n1 kubectl port-forward'
alias wkpfn='watch -n1 kubectl port-forward --namespace'
alias wkrm='watch -n1 kubectl delete'
alias wkrmall='watch -n1 kubectl delete --all'
alias wkrmcm='watch -n1 kubectl delete configmap'
alias wkrmcmall='watch -n1 kubectl delete configmap --all'
alias wkrmcml='watch -n1 kubectl delete configmap -l'
alias wkrmcmn='watch -n1 kubectl delete configmap --namespace'
alias wkrmdep='watch -n1 kubectl delete deployment'
alias wkrmdepall='watch -n1 kubectl delete deployment --all'
alias wkrmdepl='watch -n1 kubectl delete deployment -l'
alias wkrmdepn='watch -n1 kubectl delete deployment --namespace'
alias wkrmf='watch -n1 kubectl delete --recursive -f'
alias wkrming='watch -n1 kubectl delete ingress'
alias wkrmingall='watch -n1 kubectl delete ingress --all'
alias wkrmingl='watch -n1 kubectl delete ingress -l'
alias wkrmingn='watch -n1 kubectl delete ingress --namespace'
alias wkrml='watch -n1 kubectl delete -l'
alias wkrmn='watch -n1 kubectl delete --namespace'
alias wkrmns='watch -n1 kubectl delete namespaces'
alias wkrmnsall='watch -n1 kubectl delete namespaces --all'
alias wkrmnsl='watch -n1 kubectl delete namespaces -l'
alias wkrmpo='watch -n1 kubectl delete pods'
alias wkrmpoall='watch -n1 kubectl delete pods --all'
alias wkrmpol='watch -n1 kubectl delete pods -l'
alias wkrmpon='watch -n1 kubectl delete pods --namespace'
alias wkrmsec='watch -n1 kubectl delete secret'
alias wkrmsecall='watch -n1 kubectl delete secret --all'
alias wkrmsecl='watch -n1 kubectl delete secret -l'
alias wkrmsecn='watch -n1 kubectl delete secret --namespace'
alias wkrmsvc='watch -n1 kubectl delete service'
alias wkrmsvcall='watch -n1 kubectl delete service --all'
alias wkrmsvcl='watch -n1 kubectl delete service -l'
alias wkrmsvcn='watch -n1 kubectl delete service --namespace'
alias wkrun='watch -n1 kubectl run --rm --restart=Never --image-pull-policy=IfNotPresent -i -t'
alias wksys='watch -n1 kubectl --namespace=kube-system'
alias wksysa='watch -n1 kubectl --namespace=kube-system apply --recursive -f'
alias wksysd='watch -n1 kubectl --namespace=kube-system describe'
alias wksysdcm='watch -n1 kubectl --namespace=kube-system describe configmap'
alias wksysdcml='watch -n1 kubectl --namespace=kube-system describe configmap -l'
alias wksysddep='watch -n1 kubectl --namespace=kube-system describe deployment'
alias wksysddepl='watch -n1 kubectl --namespace=kube-system describe deployment -l'
alias wksysding='watch -n1 kubectl --namespace=kube-system describe ingress'
alias wksysdingl='watch -n1 kubectl --namespace=kube-system describe ingress -l'
alias wksysdl='watch -n1 kubectl --namespace=kube-system describe -l'
alias wksysdpo='watch -n1 kubectl --namespace=kube-system describe pods'
alias wksysdpol='watch -n1 kubectl --namespace=kube-system describe pods -l'
alias wksysdsec='watch -n1 kubectl --namespace=kube-system describe secret'
alias wksysdsecl='watch -n1 kubectl --namespace=kube-system describe secret -l'
alias wksysdsvc='watch -n1 kubectl --namespace=kube-system describe service'
alias wksysdsvcl='watch -n1 kubectl --namespace=kube-system describe service -l'
alias wksysex='watch -n1 kubectl --namespace=kube-system exec -i -t'
alias wksysg='watch -n1 kubectl --namespace=kube-system get'
alias wksysgcm='watch -n1 kubectl --namespace=kube-system get configmap'
alias wksysgcml='watch -n1 kubectl --namespace=kube-system get configmap -l'
alias wksysgcmojson='watch -n1 kubectl --namespace=kube-system get configmap -o=json'
alias wksysgcmojsonl='watch -n1 kubectl --namespace=kube-system get configmap -o=json -l'
alias wksysgcmowide='watch -n1 kubectl --namespace=kube-system get configmap -o=wide'
alias wksysgcmowidel='watch -n1 kubectl --namespace=kube-system get configmap -o=wide -l'
alias wksysgcmoyaml='watch -n1 kubectl --namespace=kube-system get configmap -o=yaml'
alias wksysgcmoyamll='watch -n1 kubectl --namespace=kube-system get configmap -o=yaml -l'
alias wksysgcmw='watch -n1 kubectl --namespace=kube-system get configmap --watch'
alias wksysgcmwl='watch -n1 kubectl --namespace=kube-system get configmap --watch -l'
alias wksysgcmwojson='watch -n1 kubectl --namespace=kube-system get configmap --watch -o=json'
alias wksysgcmwojsonl='watch -n1 kubectl --namespace=kube-system get configmap --watch -o=json -l'
alias wksysgcmwowide='watch -n1 kubectl --namespace=kube-system get configmap --watch -o=wide'
alias wksysgcmwowidel='watch -n1 kubectl --namespace=kube-system get configmap --watch -o=wide -l'
alias wksysgcmwoyaml='watch -n1 kubectl --namespace=kube-system get configmap --watch -o=yaml'
alias wksysgcmwoyamll='watch -n1 kubectl --namespace=kube-system get configmap --watch -o=yaml -l'
alias wksysgdep='watch -n1 kubectl --namespace=kube-system get deployment'
alias wksysgdepl='watch -n1 kubectl --namespace=kube-system get deployment -l'
alias wksysgdepojson='watch -n1 kubectl --namespace=kube-system get deployment -o=json'
alias wksysgdepojsonl='watch -n1 kubectl --namespace=kube-system get deployment -o=json -l'
alias wksysgdepowide='watch -n1 kubectl --namespace=kube-system get deployment -o=wide'
alias wksysgdepowidel='watch -n1 kubectl --namespace=kube-system get deployment -o=wide -l'
alias wksysgdepowidesl='watch -n1 kubectl --namespace=kube-system get deployment -o=wide --show-labels'
alias wksysgdepowidesll='watch -n1 kubectl --namespace=kube-system get deployment -o=wide --show-labels -l'
alias wksysgdepoyaml='watch -n1 kubectl --namespace=kube-system get deployment -o=yaml'
alias wksysgdepoyamll='watch -n1 kubectl --namespace=kube-system get deployment -o=yaml -l'
alias wksysgdepsl='watch -n1 kubectl --namespace=kube-system get deployment --show-labels'
alias wksysgdepsll='watch -n1 kubectl --namespace=kube-system get deployment --show-labels -l'
alias wksysgdepslowide='watch -n1 kubectl --namespace=kube-system get deployment --show-labels -o=wide'
alias wksysgdepslowidel='watch -n1 kubectl --namespace=kube-system get deployment --show-labels -o=wide -l'
alias wksysgdepslw='watch -n1 kubectl --namespace=kube-system get deployment --show-labels --watch'
alias wksysgdepslwl='watch -n1 kubectl --namespace=kube-system get deployment --show-labels --watch -l'
alias wksysgdepslwowide='watch -n1 kubectl --namespace=kube-system get deployment --show-labels --watch -o=wide'
alias wksysgdepslwowidel='watch -n1 kubectl --namespace=kube-system get deployment --show-labels --watch -o=wide -l'
alias wksysgdepw='watch -n1 kubectl --namespace=kube-system get deployment --watch'
alias wksysgdepwl='watch -n1 kubectl --namespace=kube-system get deployment --watch -l'
alias wksysgdepwojson='watch -n1 kubectl --namespace=kube-system get deployment --watch -o=json'
alias wksysgdepwojsonl='watch -n1 kubectl --namespace=kube-system get deployment --watch -o=json -l'
alias wksysgdepwowide='watch -n1 kubectl --namespace=kube-system get deployment --watch -o=wide'
alias wksysgdepwowidel='watch -n1 kubectl --namespace=kube-system get deployment --watch -o=wide -l'
alias wksysgdepwowidesl='watch -n1 kubectl --namespace=kube-system get deployment --watch -o=wide --show-labels'
alias wksysgdepwowidesll='watch -n1 kubectl --namespace=kube-system get deployment --watch -o=wide --show-labels -l'
alias wksysgdepwoyaml='watch -n1 kubectl --namespace=kube-system get deployment --watch -o=yaml'
alias wksysgdepwoyamll='watch -n1 kubectl --namespace=kube-system get deployment --watch -o=yaml -l'
alias wksysgdepwsl='watch -n1 kubectl --namespace=kube-system get deployment --watch --show-labels'
alias wksysgdepwsll='watch -n1 kubectl --namespace=kube-system get deployment --watch --show-labels -l'
alias wksysgdepwslowide='watch -n1 kubectl --namespace=kube-system get deployment --watch --show-labels -o=wide'
alias wksysgdepwslowidel='watch -n1 kubectl --namespace=kube-system get deployment --watch --show-labels -o=wide -l'
alias wksysging='watch -n1 kubectl --namespace=kube-system get ingress'
alias wksysgingl='watch -n1 kubectl --namespace=kube-system get ingress -l'
alias wksysgingojson='watch -n1 kubectl --namespace=kube-system get ingress -o=json'
alias wksysgingojsonl='watch -n1 kubectl --namespace=kube-system get ingress -o=json -l'
alias wksysgingowide='watch -n1 kubectl --namespace=kube-system get ingress -o=wide'
alias wksysgingowidel='watch -n1 kubectl --namespace=kube-system get ingress -o=wide -l'
alias wksysgingoyaml='watch -n1 kubectl --namespace=kube-system get ingress -o=yaml'
alias wksysgingoyamll='watch -n1 kubectl --namespace=kube-system get ingress -o=yaml -l'
alias wksysgingw='watch -n1 kubectl --namespace=kube-system get ingress --watch'
alias wksysgingwl='watch -n1 kubectl --namespace=kube-system get ingress --watch -l'
alias wksysgingwojson='watch -n1 kubectl --namespace=kube-system get ingress --watch -o=json'
alias wksysgingwojsonl='watch -n1 kubectl --namespace=kube-system get ingress --watch -o=json -l'
alias wksysgingwowide='watch -n1 kubectl --namespace=kube-system get ingress --watch -o=wide'
alias wksysgingwowidel='watch -n1 kubectl --namespace=kube-system get ingress --watch -o=wide -l'
alias wksysgingwoyaml='watch -n1 kubectl --namespace=kube-system get ingress --watch -o=yaml'
alias wksysgingwoyamll='watch -n1 kubectl --namespace=kube-system get ingress --watch -o=yaml -l'
alias wksysgl='watch -n1 kubectl --namespace=kube-system get -l'
alias wksysgojson='watch -n1 kubectl --namespace=kube-system get -o=json'
alias wksysgojsonl='watch -n1 kubectl --namespace=kube-system get -o=json -l'
alias wksysgowide='watch -n1 kubectl --namespace=kube-system get -o=wide'
alias wksysgowidel='watch -n1 kubectl --namespace=kube-system get -o=wide -l'
alias wksysgowidesl='watch -n1 kubectl --namespace=kube-system get -o=wide --show-labels'
alias wksysgowidesll='watch -n1 kubectl --namespace=kube-system get -o=wide --show-labels -l'
alias wksysgoyaml='watch -n1 kubectl --namespace=kube-system get -o=yaml'
alias wksysgoyamll='watch -n1 kubectl --namespace=kube-system get -o=yaml -l'
alias wksysgpo='watch -n1 kubectl --namespace=kube-system get pods'
alias wksysgpol='watch -n1 kubectl --namespace=kube-system get pods -l'
alias wksysgpoojson='watch -n1 kubectl --namespace=kube-system get pods -o=json'
alias wksysgpoojsonl='watch -n1 kubectl --namespace=kube-system get pods -o=json -l'
alias wksysgpoowide='watch -n1 kubectl --namespace=kube-system get pods -o=wide'
alias wksysgpoowidel='watch -n1 kubectl --namespace=kube-system get pods -o=wide -l'
alias wksysgpoowidesl='watch -n1 kubectl --namespace=kube-system get pods -o=wide --show-labels'
alias wksysgpoowidesll='watch -n1 kubectl --namespace=kube-system get pods -o=wide --show-labels -l'
alias wksysgpooyaml='watch -n1 kubectl --namespace=kube-system get pods -o=yaml'
alias wksysgpooyamll='watch -n1 kubectl --namespace=kube-system get pods -o=yaml -l'
alias wksysgposl='watch -n1 kubectl --namespace=kube-system get pods --show-labels'
alias wksysgposll='watch -n1 kubectl --namespace=kube-system get pods --show-labels -l'
alias wksysgposlowide='watch -n1 kubectl --namespace=kube-system get pods --show-labels -o=wide'
alias wksysgposlowidel='watch -n1 kubectl --namespace=kube-system get pods --show-labels -o=wide -l'
alias wksysgposlw='watch -n1 kubectl --namespace=kube-system get pods --show-labels --watch'
alias wksysgposlwl='watch -n1 kubectl --namespace=kube-system get pods --show-labels --watch -l'
alias wksysgposlwowide='watch -n1 kubectl --namespace=kube-system get pods --show-labels --watch -o=wide'
alias wksysgposlwowidel='watch -n1 kubectl --namespace=kube-system get pods --show-labels --watch -o=wide -l'
alias wksysgpow='watch -n1 kubectl --namespace=kube-system get pods --watch'
alias wksysgpowl='watch -n1 kubectl --namespace=kube-system get pods --watch -l'
alias wksysgpowojson='watch -n1 kubectl --namespace=kube-system get pods --watch -o=json'
alias wksysgpowojsonl='watch -n1 kubectl --namespace=kube-system get pods --watch -o=json -l'
alias wksysgpowowide='watch -n1 kubectl --namespace=kube-system get pods --watch -o=wide'
alias wksysgpowowidel='watch -n1 kubectl --namespace=kube-system get pods --watch -o=wide -l'
alias wksysgpowowidesl='watch -n1 kubectl --namespace=kube-system get pods --watch -o=wide --show-labels'
alias wksysgpowowidesll='watch -n1 kubectl --namespace=kube-system get pods --watch -o=wide --show-labels -l'
alias wksysgpowoyaml='watch -n1 kubectl --namespace=kube-system get pods --watch -o=yaml'
alias wksysgpowoyamll='watch -n1 kubectl --namespace=kube-system get pods --watch -o=yaml -l'
alias wksysgpowsl='watch -n1 kubectl --namespace=kube-system get pods --watch --show-labels'
alias wksysgpowsll='watch -n1 kubectl --namespace=kube-system get pods --watch --show-labels -l'
alias wksysgpowslowide='watch -n1 kubectl --namespace=kube-system get pods --watch --show-labels -o=wide'
alias wksysgpowslowidel='watch -n1 kubectl --namespace=kube-system get pods --watch --show-labels -o=wide -l'
alias wksysgsec='watch -n1 kubectl --namespace=kube-system get secret'
alias wksysgsecl='watch -n1 kubectl --namespace=kube-system get secret -l'
alias wksysgsecojson='watch -n1 kubectl --namespace=kube-system get secret -o=json'
alias wksysgsecojsonl='watch -n1 kubectl --namespace=kube-system get secret -o=json -l'
alias wksysgsecowide='watch -n1 kubectl --namespace=kube-system get secret -o=wide'
alias wksysgsecowidel='watch -n1 kubectl --namespace=kube-system get secret -o=wide -l'
alias wksysgsecoyaml='watch -n1 kubectl --namespace=kube-system get secret -o=yaml'
alias wksysgsecoyamll='watch -n1 kubectl --namespace=kube-system get secret -o=yaml -l'
alias wksysgsecw='watch -n1 kubectl --namespace=kube-system get secret --watch'
alias wksysgsecwl='watch -n1 kubectl --namespace=kube-system get secret --watch -l'
alias wksysgsecwojson='watch -n1 kubectl --namespace=kube-system get secret --watch -o=json'
alias wksysgsecwojsonl='watch -n1 kubectl --namespace=kube-system get secret --watch -o=json -l'
alias wksysgsecwowide='watch -n1 kubectl --namespace=kube-system get secret --watch -o=wide'
alias wksysgsecwowidel='watch -n1 kubectl --namespace=kube-system get secret --watch -o=wide -l'
alias wksysgsecwoyaml='watch -n1 kubectl --namespace=kube-system get secret --watch -o=yaml'
alias wksysgsecwoyamll='watch -n1 kubectl --namespace=kube-system get secret --watch -o=yaml -l'
alias wksysgsl='watch -n1 kubectl --namespace=kube-system get --show-labels'
alias wksysgsll='watch -n1 kubectl --namespace=kube-system get --show-labels -l'
alias wksysgslowide='watch -n1 kubectl --namespace=kube-system get --show-labels -o=wide'
alias wksysgslowidel='watch -n1 kubectl --namespace=kube-system get --show-labels -o=wide -l'
alias wksysgslw='watch -n1 kubectl --namespace=kube-system get --show-labels --watch'
alias wksysgslwl='watch -n1 kubectl --namespace=kube-system get --show-labels --watch -l'
alias wksysgslwowide='watch -n1 kubectl --namespace=kube-system get --show-labels --watch -o=wide'
alias wksysgslwowidel='watch -n1 kubectl --namespace=kube-system get --show-labels --watch -o=wide -l'
alias wksysgsvc='watch -n1 kubectl --namespace=kube-system get service'
alias wksysgsvcl='watch -n1 kubectl --namespace=kube-system get service -l'
alias wksysgsvcojson='watch -n1 kubectl --namespace=kube-system get service -o=json'
alias wksysgsvcojsonl='watch -n1 kubectl --namespace=kube-system get service -o=json -l'
alias wksysgsvcowide='watch -n1 kubectl --namespace=kube-system get service -o=wide'
alias wksysgsvcowidel='watch -n1 kubectl --namespace=kube-system get service -o=wide -l'
alias wksysgsvcoyaml='watch -n1 kubectl --namespace=kube-system get service -o=yaml'
alias wksysgsvcoyamll='watch -n1 kubectl --namespace=kube-system get service -o=yaml -l'
alias wksysgsvcw='watch -n1 kubectl --namespace=kube-system get service --watch'
alias wksysgsvcwl='watch -n1 kubectl --namespace=kube-system get service --watch -l'
alias wksysgsvcwojson='watch -n1 kubectl --namespace=kube-system get service --watch -o=json'
alias wksysgsvcwojsonl='watch -n1 kubectl --namespace=kube-system get service --watch -o=json -l'
alias wksysgsvcwowide='watch -n1 kubectl --namespace=kube-system get service --watch -o=wide'
alias wksysgsvcwowidel='watch -n1 kubectl --namespace=kube-system get service --watch -o=wide -l'
alias wksysgsvcwoyaml='watch -n1 kubectl --namespace=kube-system get service --watch -o=yaml'
alias wksysgsvcwoyamll='watch -n1 kubectl --namespace=kube-system get service --watch -o=yaml -l'
alias wksysgw='watch -n1 kubectl --namespace=kube-system get --watch'
alias wksysgwl='watch -n1 kubectl --namespace=kube-system get --watch -l'
alias wksysgwojson='watch -n1 kubectl --namespace=kube-system get --watch -o=json'
alias wksysgwojsonl='watch -n1 kubectl --namespace=kube-system get --watch -o=json -l'
alias wksysgwowide='watch -n1 kubectl --namespace=kube-system get --watch -o=wide'
alias wksysgwowidel='watch -n1 kubectl --namespace=kube-system get --watch -o=wide -l'
alias wksysgwowidesl='watch -n1 kubectl --namespace=kube-system get --watch -o=wide --show-labels'
alias wksysgwowidesll='watch -n1 kubectl --namespace=kube-system get --watch -o=wide --show-labels -l'
alias wksysgwoyaml='watch -n1 kubectl --namespace=kube-system get --watch -o=yaml'
alias wksysgwoyamll='watch -n1 kubectl --namespace=kube-system get --watch -o=yaml -l'
alias wksysgwsl='watch -n1 kubectl --namespace=kube-system get --watch --show-labels'
alias wksysgwsll='watch -n1 kubectl --namespace=kube-system get --watch --show-labels -l'
alias wksysgwslowide='watch -n1 kubectl --namespace=kube-system get --watch --show-labels -o=wide'
alias wksysgwslowidel='watch -n1 kubectl --namespace=kube-system get --watch --show-labels -o=wide -l'
alias wksyslo='watch -n1 kubectl --namespace=kube-system logs -f'
alias wksyslop='watch -n1 kubectl --namespace=kube-system logs -f -p'
alias wksysrm='watch -n1 kubectl --namespace=kube-system delete'
alias wksysrmall='watch -n1 kubectl --namespace=kube-system delete --all'
alias wksysrmcm='watch -n1 kubectl --namespace=kube-system delete configmap'
alias wksysrmcmall='watch -n1 kubectl --namespace=kube-system delete configmap --all'
alias wksysrmcml='watch -n1 kubectl --namespace=kube-system delete configmap -l'
alias wksysrmdep='watch -n1 kubectl --namespace=kube-system delete deployment'
alias wksysrmdepall='watch -n1 kubectl --namespace=kube-system delete deployment --all'
alias wksysrmdepl='watch -n1 kubectl --namespace=kube-system delete deployment -l'
alias wksysrming='watch -n1 kubectl --namespace=kube-system delete ingress'
alias wksysrmingall='watch -n1 kubectl --namespace=kube-system delete ingress --all'
alias wksysrmingl='watch -n1 kubectl --namespace=kube-system delete ingress -l'
alias wksysrml='watch -n1 kubectl --namespace=kube-system delete -l'
alias wksysrmpo='watch -n1 kubectl --namespace=kube-system delete pods'
alias wksysrmpoall='watch -n1 kubectl --namespace=kube-system delete pods --all'
alias wksysrmpol='watch -n1 kubectl --namespace=kube-system delete pods -l'
alias wksysrmsec='watch -n1 kubectl --namespace=kube-system delete secret'
alias wksysrmsecall='watch -n1 kubectl --namespace=kube-system delete secret --all'
alias wksysrmsecl='watch -n1 kubectl --namespace=kube-system delete secret -l'
alias wksysrmsvc='watch -n1 kubectl --namespace=kube-system delete service'
alias wksysrmsvcall='watch -n1 kubectl --namespace=kube-system delete service --all'
alias wksysrmsvcl='watch -n1 kubectl --namespace=kube-system delete service -l'
alias wksysrun='watch -n1 kubectl --namespace=kube-system run --rm --restart=Never --image-pull-policy=IfNotPresent -i -t'
