apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base/
- helmrelease-csr-auto-approver.yaml
- helmrelease-metallb.yaml
- helmrelease-kube-vip-cloud-provider.yaml
- helmrelease-metrics-server.yaml

patches:
- path: excludes.yaml
