tls_min_version: "VersionTLS13"

#searchdomains:
#- example.com

#nameservers:
#- 8.8.8.8
#- 1.1.1.1

## ETCD-BACKUP
#etcd_backup_s3_bucket: 'bucket-name'
#etcd_backup_aws_access_key_id: ''
#etcd_backup_aws_secret_access_key: ''

## KUBE-VIP
##
## Kube-VIP must be installed by kubespray, not flux, because apiserver's IP address must
## be included in the certificate SANs for the apiserver.
##
## To configure kube-vip, edit the vars kube_vip_* from k8s_cluster/addons.yml
kube_vip_arp_enabled: true
kube_proxy_strict_arp: true ## kube-vip in arp mode requires strict-arp in ipvsX interfaces

kubeconfig_localhost: true

kubelet_rotate_server_certificates: true

## Automatically renew K8S control plane certificates on first Monday of each month

### NOTICE ###
### The option below must be disable in group_vars/k8s_cluster/k8s-cluster.yml
auto_renew_certificates: true
### NOTICE ###

# First Monday of each month
# Timer Format: DayOfWeek Year-Month-Day Hour:Minute:Second
auto_renew_certificates_systemd_calendar: "Mon *-2,7-1,2,3,4,5,6,7 03:{{ groups['kube_control_plane'].index(inventory_hostname) }}0:00"

# https://github.com/postfinance/kubelet-csr-approver/blob/main/charts/kubelet-csr-approver/values.yaml
kubelet_csr_approver_values:
  # optional, permits to bypass dns resolution checks. default: false
  bypassDnsResolution: true
  # number of DNS SAN names allowed in a certificate request. defaults to 1
  allowedDnsNames: 3

additional_sysctl:
## File-system related
- name: fs.aio-max-nr
  value: 1048576
- name: fs.file-max
  value: 104857600
- name: fs.nr_open
  value: 10485760
- name: fs.inotify.max_user_instances
  value: 1048576
- name: fs.inotify.max_user_watches
  value: 1048576
## Process related
- name: kernel.pid_max
  value: 128000
- name: kernel.threads-max
  value: 128000
## Network performance related
- name: net.core.rmem_max
  value: 2129920
- name: net.core.wmem_max
  value: 2129920
- name: net.core.netdev_max_backlog
  value: 65536
- name: net.netfilter.nf_conntrack_max
  value: 524288
- name: net.ipv4.tcp_max_syn_backlog
  value: 10240
- name: net.core.somaxconn
  value: 65536
- name: net.ipv4.tcp_fin_timeout
  value: 30
- name: net.ipv4.neigh.default.gc_thresh1
  value: 1000
- name: net.ipv4.neigh.default.gc_thresh2
  value: 2000
- name: net.ipv4.neigh.default.gc_thresh3
  value: 3000
- name: net.ipv4.ip_local_port_range
  value: 32768 62768


kubernetes_audit: true
audit_log_maxage: 3
audit_policy_custom_rules: |
  - level: RequestResponse
    users: []
    verbs:
    - create
    - update
    - patch
    - delete
    - deletecollection
    - bind
    resources: []
    namespaces: []
  - level: RequestResponse
    verbs:
    - get
    - watch
    namespaces: []
    resources:
     - group: ""
      resources:
      - pods
    resources:
    - pods/exec

ignored_audit_rules: # remove this to take effect
    ## Default audit config from kubespray
    ## roles/kubernetes/control-plane/templates/apiserver-audit-policy.yaml.j2

    # The following requests were manually identified as high-volume and low-risk,
    # so drop them.
    - level: None
      users: ["system:kube-proxy"]
      verbs: ["watch"]
      resources:
        - group: "" # core
          resources: ["endpoints", "services", "services/status"]
    - level: None
      # Ingress controller reads `configmaps/ingress-uid` through the unsecured port.
      # TODO(#46983): Change this to the ingress controller service account.
      users: ["system:unsecured"]
      namespaces: ["kube-system"]
      verbs: ["get"]
      resources:
        - group: "" # core
          resources: ["configmaps"]
    - level: None
      users: ["kubelet"] # legacy kubelet identity
      verbs: ["get"]
      resources:
        - group: "" # core
          resources: ["nodes", "nodes/status"]
    - level: None
      userGroups: ["system:nodes"]
      verbs: ["get"]
      resources:
        - group: "" # core
          resources: ["nodes", "nodes/status"]
    - level: None
      users:
        - system:kube-controller-manager
        - system:kube-scheduler
        - system:serviceaccount:kube-system:endpoint-controller
      verbs: ["get", "update"]
      namespaces: ["kube-system"]
      resources:
        - group: "" # core
          resources: ["endpoints"]
    - level: None
      users: ["system:apiserver"]
      verbs: ["get"]
      resources:
        - group: "" # core
          resources: ["namespaces", "namespaces/status", "namespaces/finalize"]
    # Don't log HPA fetching metrics.
    - level: None
      users:
        - system:kube-controller-manager
      verbs: ["get", "list"]
      resources:
        - group: "metrics.k8s.io"
    # Don't log these read-only URLs.
    - level: None
      nonResourceURLs:
        - /healthz*
        - /version
        - /swagger*
    # Don't log events requests.
    - level: None
      resources:
        - group: "" # core
          resources: ["events"]
    # Secrets, ConfigMaps, TokenRequest and TokenReviews can contain sensitive & binary data,
    # so only log at the Metadata level.
    - level: Metadata
      resources:
        - group: "" # core
          resources: ["secrets", "configmaps", "serviceaccounts/token"]
        - group: authentication.k8s.io
          resources: ["tokenreviews"]
      omitStages:
        - "RequestReceived"
    # Get responses can be large; skip them.
    - level: Request
      verbs: ["get", "list", "watch"]
      resources:
        - group: "" # core
        - group: "admissionregistration.k8s.io"
        - group: "apiextensions.k8s.io"
        - group: "apiregistration.k8s.io"
        - group: "apps"
        - group: "authentication.k8s.io"
        - group: "authorization.k8s.io"
        - group: "autoscaling"
        - group: "batch"
        - group: "certificates.k8s.io"
        - group: "extensions"
        - group: "metrics.k8s.io"
        - group: "networking.k8s.io"
        - group: "policy"
        - group: "rbac.authorization.k8s.io"
        - group: "settings.k8s.io"
        - group: "storage.k8s.io"
      omitStages:
        - "RequestReceived"
    # Default level for known APIs
    - level: RequestResponse
      resources:
        - group: "" # core
        - group: "admissionregistration.k8s.io"
        - group: "apiextensions.k8s.io"
        - group: "apiregistration.k8s.io"
        - group: "apps"
        - group: "authentication.k8s.io"
        - group: "authorization.k8s.io"
        - group: "autoscaling"
        - group: "batch"
        - group: "certificates.k8s.io"
        - group: "extensions"
        - group: "metrics.k8s.io"
        - group: "networking.k8s.io"
        - group: "policy"
        - group: "rbac.authorization.k8s.io"
        - group: "settings.k8s.io"
        - group: "storage.k8s.io"
      omitStages:
        - "RequestReceived"
    # Default level for all other requests.
    - level: Metadata
      omitStages:
        - "RequestReceived"

