##
## MUST configure VMs following the instructions from
## https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/container-storage-plugin/3-0/getting-started-with-vmware-vsphere-container-storage-plug-in-3-0/vsphere-container-storage-plug-in-deployment/preparing-for-installation-of-vsphere-container-storage-plug-in.html#GUID-0AB6E692-AA47-4B6A-8CEA-38B754E16567-en
## Section: Configure Kubernetes Cluster VMs
##
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: vsphere
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.vsphere.vmware.com
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
#parameters:
#  csi.storage.k8s.io/fstype: "ext4"   ## select filesystem: "ext4" (default), "ext3", "xfs", "nfs4", "nfs", "ntfs"
#  datastoreurl: ds:///vmfs/volumes/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/       ## note required trailing /
#  datastoreurl: ds:///vmfs/volumes/vsan:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/  ## same, but for vSAN
