apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base/

patches:
- path: helmrelease-ingress-nginx.yaml
- path: helmrelease-logging.yaml
- path: helmrelease-monitoring.yaml
- path: helmrelease-velero.yaml
