apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: falco
  namespace: flux-system
spec:
  suspend: true
  chart:
    spec:
      chart: falco
      sourceRef:
        kind: HelmRepository
        name: falcosecurity
  install:
    createNamespace: true
    disableWait: true
    remediation:
      retries: -1
  upgrade:
    disableWait: false
    remediation:
      retries: -1
  interval: 5m
  releaseName: falco
  storageNamespace: kube-system
  targetNamespace: kube-system
  values:
    #auditLog:
    #  enabled: true

    ebpf:
      enabled: true

    falco:
      grpc:
        enabled: true
      grpcOutput:
        enabled: true

      logSyslog: true

    tolerations:
    - effect: NoSchedule
      operator: Exists
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: falco-exporter
  namespace: flux-system
spec:
  suspend: true
  chart:
    spec:
      chart: falco-exporter
      sourceRef:
        kind: HelmRepository
        name: falcosecurity
  install:
    createNamespace: true
    disableWait: true
    remediation:
      retries: -1
  upgrade:
    disableWait: false
    remediation:
      retries: -1
  interval: 5m
  releaseName: falco-exporter
  storageNamespace: kube-system
  targetNamespace: kube-system
  values:
    serviceMonitor:
      enabled: true
      interval: "15s"

    prometheusRules:
      enabled: true

    grafanaDashboard:
      enabled: true
      namespace: monitoring

    tolerations:
    - effect: NoSchedule
      operator: Exists
