apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
      version: 1.8.0
  dependsOn: []
  install:
    createNamespace: true
    disableWait: false
    remediation:
      retries: -1
  upgrade:
    disableWait: false
    remediation:
      retries: -1
  interval: 5m
  releaseName: cert-manager
  storageNamespace: cert-manager
  targetNamespace: cert-manager
  values:
    installCRDs: true

    prometheus:
      servicemonitor:
        enabled: true

    tolerations:
    - key: dedicated
      value: infra
      effect: NoSchedule
    - key: CriticalAddonsOnly
      effect: NoSchedule

    nodeSelector:
      role: infra

    cainjector:
      nodeSelector:
        role: infra
      tolerations:
      - key: dedicated
        value: infra
        effect: NoSchedule
      - key: CriticalAddonsOnly
        effect: NoSchedule

    webhook:
      nodeSelector:
        role: infra
      tolerations:
      - key: dedicated
        value: infra
        effect: NoSchedule
      - key: CriticalAddonsOnly
        effect: NoSchedule
