apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  annotations: {}
  name: velero-config
  namespace: flux-system
spec:
  chart:
    spec:
      chart: velero-config
      sourceRef:
        kind: HelmRepository
        name: getupcloud
  dependsOn:
    - name: velero
  install:
    createNamespace: true
    disableWait: false
    remediation:
      retries: -1
  upgrade:
    disableWait: false
    remediation:
      retries: -1
  interval: 5m
  releaseName: velero-config
  storageNamespace: velero
  targetNamespace: velero
  values:
    schedules:
      storageClasses:
        enabled: true
        schedule: '0 0 */7 * *'
        ttl: 720h0m0s
        storageLocation: default
        #labelSelector: {}
    
      volumes:
        enabled: true
        schedule: '0 3 * * *'
        ttl: 168h0m0s
        storageLocation: default
        #labelSelector: {}
    
      resources:
        enabled: true
        schedule: '0 */12 * * *'
        ttl: 720h0m0s
        storageLocation: default
        includedNamespaces:
        - "*"
        excludedNamespaces:
        - kube-system
        - kube-public
        - monitoring
        - velero
        includedResources:
        - "*"
        includeClusterResources: true
        #labelSelector: {}
