apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: flux-system
spec:
  chart:
    spec:
      chart: velero
      sourceRef:
        kind: HelmRepository
        name: velero
      version: 2.23.5
  install:
    createNamespace: true
    disableWait: false
    remediation:
      retries: -1
  upgrade:
    disableWait: false
    remediation:
      retries: -1
  interval: 5m
  storageNamespace: velero
  targetNamespace: velero
  releaseName: velero
  values:
    configuration:
      backupStorageLocation:
        name: default

      volumeSnapshotLocation:
        name: default

    credentials:
      useSecret: true
      secretContents:
        cloud: ""

    tolerations:
    - effect: NoSchedule
      key: dedicated
      value: infra
    - effect: NoSchedule
      key: CriticalAddonsOnly

    nodeSelector:
      role: infra

    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 1Gi
        cpu: 500m

    metrics:
      enabled: true
