---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  chart:
    spec:
      chart: metrics-server
      sourceRef:
        kind: HelmRepository
        name: metrics-server
      version: "~> 3.8"
  releaseName: metrics-server
  install:
    createNamespace: true
    disableWait: false
    remediation:
      retries: -1
  upgrade:
    disableWait: false
    remediation:
      retries: -1
  interval: 5m
  targetNamespace: kube-system
  storageNamespace: kube-system
  values:
    args:
    - --kubelet-insecure-tls
    metrics:
      enabled: true
    serviceMonitor:
      enabled: false
